export interface ITextHomeData {
  id?: string,
  container1Title: string,
  container1Subtitle: string,
  container1Button: string,
  container2Title: string,
  container2Text1: string,
  container2Text2: string,
  container2Card1Title: string,
  container2Card1Text: string,
  container2Card2Title: string,
  container2Card2Text: string,
  container2Card3Title: string,
  container2Card3Text: string,
  container3Title: string,
  container3Card1Title: string,
  container3Card1Subtitle: string,
  container3Card1List: string,
  container3Card2Title: string,
  container3Card2Subtitle: string,
  container3Card2List: string,
};
